In [1]:
from scipy import signal
import numpy as np

In [2]:
# Continuous transfer function
w0 = 2*np.pi*35
num = w0
den = [1, w0]
lowPass = signal.TransferFunction(num, den)
print(lowPass)

TransferFunctionContinuous(
array([219.91148575]),
array([  1.        , 219.91148575]),
dt: None
)


In [3]:
# Discrete transfer function
dt = 1.0/1000.0
discreteLowPass = lowPass.to_discrete(dt, method='gbt',alpha=0.5)
print(discreteLowPass)

TransferFunctionDiscrete(
array([0.09906318, 0.09906318]),
array([ 1.        , -0.80187364]),
dt: 0.001
)


In [4]:
# Difference equation coefficients
b = discreteLowPass.num
a = -discreteLowPass.den
print("Filter coefficients a_i: " +  str(a[1:]))
print("Filter coefficients b_i: " +  str(b))

Filter coefficients a_i: [0.80187364]
Filter coefficients b_i: [0.09906318 0.09906318]
